version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: fsw-barber-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fsw-barber
    ports:
      - "5433:5433"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data: